name: Docker

on:
  workflow_call: 

jobs:
  download_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Writing step summary
        run: |
          echo "Downloading the image!" >> $GITHUB_STEP_SUMMARY
          echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "Run id: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.1
        with:
          name: Go API
  
  docker:
    needs: download_image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.USER_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: icl00ud/go_ci:${{ github.ref_name }}
          
